#!/bin/bash
./ansiu asc/3d_rotation.asc; sleep 1
./ansiu asc/access_alarm.asc; sleep 1
./ansiu asc/access_alarms.asc; sleep 1
./ansiu asc/accessibility.asc; sleep 1
./ansiu asc/accessible.asc; sleep 1
./ansiu asc/access_time.asc; sleep 1
./ansiu asc/account_balance.asc; sleep 1
./ansiu asc/account_balance_wallet.asc; sleep 1
./ansiu asc/account_box.asc; sleep 1
./ansiu asc/account_circle.asc; sleep 1
./ansiu asc/ac_unit.asc; sleep 1
./ansiu asc/adb.asc; sleep 1
./ansiu asc/add_alarm.asc; sleep 1
./ansiu asc/add_alert.asc; sleep 1
./ansiu asc/add_a_photo.asc; sleep 1
./ansiu asc/add.asc; sleep 1
./ansiu asc/add_box.asc; sleep 1
./ansiu asc/add_circle.asc; sleep 1
./ansiu asc/add_circle_outline.asc; sleep 1
./ansiu asc/add_location.asc; sleep 1
./ansiu asc/add_shopping_cart.asc; sleep 1
./ansiu asc/add_to_photos.asc; sleep 1
./ansiu asc/add_to_queue.asc; sleep 1
./ansiu asc/adjust.asc; sleep 1
./ansiu asc/airline_seat_flat_angled.asc; sleep 1
./ansiu asc/airline_seat_flat.asc; sleep 1
./ansiu asc/airline_seat_individual_suite.asc; sleep 1
./ansiu asc/airline_seat_legroom_extra.asc; sleep 1
./ansiu asc/airline_seat_legroom_normal.asc; sleep 1
./ansiu asc/airline_seat_legroom_reduced.asc; sleep 1
./ansiu asc/airline_seat_recline_extra.asc; sleep 1
./ansiu asc/airline_seat_recline_normal.asc; sleep 1
./ansiu asc/airplanemode_active.asc; sleep 1
./ansiu asc/airplanemode_inactive.asc; sleep 1
./ansiu asc/airplay.asc; sleep 1
./ansiu asc/airport_shuttle.asc; sleep 1
./ansiu asc/alarm_add.asc; sleep 1
./ansiu asc/alarm.asc; sleep 1
./ansiu asc/alarm_off.asc; sleep 1
./ansiu asc/alarm_on.asc; sleep 1
./ansiu asc/album.asc; sleep 1
./ansiu asc/all_inclusive.asc; sleep 1
./ansiu asc/all_out.asc; sleep 1
./ansiu asc/android.asc; sleep 1
./ansiu asc/announcement.asc; sleep 1
./ansiu asc/apps.asc; sleep 1
./ansiu asc/archive.asc; sleep 1
./ansiu asc/arrow_back.asc; sleep 1
./ansiu asc/arrow_downward.asc; sleep 1
./ansiu asc/arrow_drop_down.asc; sleep 1
./ansiu asc/arrow_drop_down_circle.asc; sleep 1
./ansiu asc/arrow_drop_up.asc; sleep 1
./ansiu asc/arrow_forward.asc; sleep 1
./ansiu asc/arrow_upward.asc; sleep 1
./ansiu asc/art_track.asc; sleep 1
./ansiu asc/aspect_ratio.asc; sleep 1
./ansiu asc/assessment.asc; sleep 1
./ansiu asc/assignment.asc; sleep 1
./ansiu asc/assignment_ind.asc; sleep 1
./ansiu asc/assignment_late.asc; sleep 1
./ansiu asc/assignment_return.asc; sleep 1
./ansiu asc/assignment_returned.asc; sleep 1
./ansiu asc/assignment_turned_in.asc; sleep 1
./ansiu asc/assistant.asc; sleep 1
./ansiu asc/assistant_photo.asc; sleep 1
./ansiu asc/attach_file.asc; sleep 1
./ansiu asc/attachment.asc; sleep 1
./ansiu asc/attach_money.asc; sleep 1
./ansiu asc/audiotrack.asc; sleep 1
./ansiu asc/autorenew.asc; sleep 1
./ansiu asc/av_timer.asc; sleep 1
./ansiu asc/backspace.asc; sleep 1
./ansiu asc/backup.asc; sleep 1
./ansiu asc/battery_20.asc; sleep 1
./ansiu asc/battery_30.asc; sleep 1
./ansiu asc/battery_50.asc; sleep 1
./ansiu asc/battery_60.asc; sleep 1
./ansiu asc/battery_80.asc; sleep 1
./ansiu asc/battery_90.asc; sleep 1
./ansiu asc/battery_alert.asc; sleep 1
./ansiu asc/battery_charging_20.asc; sleep 1
./ansiu asc/battery_charging_30.asc; sleep 1
./ansiu asc/battery_charging_50.asc; sleep 1
./ansiu asc/battery_charging_60.asc; sleep 1
./ansiu asc/battery_charging_80.asc; sleep 1
./ansiu asc/battery_charging_90.asc; sleep 1
./ansiu asc/battery_charging_full.asc; sleep 1
./ansiu asc/battery_full.asc; sleep 1
./ansiu asc/battery_std.asc; sleep 1
./ansiu asc/battery_unknown.asc; sleep 1
./ansiu asc/beach_access.asc; sleep 1
./ansiu asc/beenhere.asc; sleep 1
./ansiu asc/block.asc; sleep 1
./ansiu asc/bluetooth_audio.asc; sleep 1
./ansiu asc/bluetooth.asc; sleep 1
./ansiu asc/bluetooth_connected.asc; sleep 1
./ansiu asc/bluetooth_disabled.asc; sleep 1
./ansiu asc/bluetooth_searching.asc; sleep 1
./ansiu asc/blur_circular.asc; sleep 1
./ansiu asc/blur_linear.asc; sleep 1
./ansiu asc/blur_off.asc; sleep 1
./ansiu asc/blur_on.asc; sleep 1
./ansiu asc/book.asc; sleep 1
./ansiu asc/bookmark.asc; sleep 1
./ansiu asc/bookmark_border.asc; sleep 1
./ansiu asc/border_all.asc; sleep 1
./ansiu asc/border_bottom.asc; sleep 1
./ansiu asc/border_clear.asc; sleep 1
./ansiu asc/border_color.asc; sleep 1
./ansiu asc/border_horizontal.asc; sleep 1
./ansiu asc/border_inner.asc; sleep 1
./ansiu asc/border_left.asc; sleep 1
./ansiu asc/border_outer.asc; sleep 1
./ansiu asc/border_right.asc; sleep 1
./ansiu asc/border_style.asc; sleep 1
./ansiu asc/border_top.asc; sleep 1
./ansiu asc/border_vertical.asc; sleep 1
./ansiu asc/branding_watermark.asc; sleep 1
./ansiu asc/brightness_1.asc; sleep 1
./ansiu asc/brightness_2.asc; sleep 1
./ansiu asc/brightness_3.asc; sleep 1
./ansiu asc/brightness_4.asc; sleep 1
./ansiu asc/brightness_5.asc; sleep 1
./ansiu asc/brightness_6.asc; sleep 1
./ansiu asc/brightness_7.asc; sleep 1
./ansiu asc/brightness_auto.asc; sleep 1
./ansiu asc/brightness_high.asc; sleep 1
./ansiu asc/brightness_low.asc; sleep 1
./ansiu asc/brightness_medium.asc; sleep 1
./ansiu asc/broken_image.asc; sleep 1
./ansiu asc/brush.asc; sleep 1
./ansiu asc/bubble_chart.asc; sleep 1
./ansiu asc/bug_report.asc; sleep 1
./ansiu asc/build.asc; sleep 1
./ansiu asc/burst_mode.asc; sleep 1
./ansiu asc/business.asc; sleep 1
./ansiu asc/business_center.asc; sleep 1
./ansiu asc/cached.asc; sleep 1
./ansiu asc/cake.asc; sleep 1
./ansiu asc/call.asc; sleep 1
./ansiu asc/call_end.asc; sleep 1
./ansiu asc/call_made.asc; sleep 1
./ansiu asc/call_merge.asc; sleep 1
./ansiu asc/call_missed.asc; sleep 1
./ansiu asc/call_missed_outgoing.asc; sleep 1
./ansiu asc/call_received.asc; sleep 1
./ansiu asc/call_split.asc; sleep 1
./ansiu asc/call_to_action.asc; sleep 1
./ansiu asc/camera_alt.asc; sleep 1
./ansiu asc/camera.asc; sleep 1
./ansiu asc/camera_enhance.asc; sleep 1
./ansiu asc/camera_front.asc; sleep 1
./ansiu asc/camera_rear.asc; sleep 1
./ansiu asc/camera_roll.asc; sleep 1
./ansiu asc/cancel.asc; sleep 1
./ansiu asc/card_giftcard.asc; sleep 1
./ansiu asc/card_membership.asc; sleep 1
./ansiu asc/card_travel.asc; sleep 1
./ansiu asc/casino.asc; sleep 1
./ansiu asc/cast.asc; sleep 1
./ansiu asc/cast_connected.asc; sleep 1
./ansiu asc/center_focus_strong.asc; sleep 1
./ansiu asc/center_focus_weak.asc; sleep 1
./ansiu asc/change_history.asc; sleep 1
./ansiu asc/chat.asc; sleep 1
./ansiu asc/chat_bubble.asc; sleep 1
./ansiu asc/chat_bubble_outline.asc; sleep 1
./ansiu asc/check.asc; sleep 1
./ansiu asc/check_box.asc; sleep 1
./ansiu asc/check_box_outline_blank.asc; sleep 1
./ansiu asc/check_circle.asc; sleep 1
./ansiu asc/chevron_left.asc; sleep 1
./ansiu asc/chevron_right.asc; sleep 1
./ansiu asc/child_care.asc; sleep 1
./ansiu asc/child_friendly.asc; sleep 1
./ansiu asc/chrome_reader_mode.asc; sleep 1
./ansiu asc/class.asc; sleep 1
./ansiu asc/clear_all.asc; sleep 1
./ansiu asc/clear.asc; sleep 1
./ansiu asc/close.asc; sleep 1
./ansiu asc/closed_caption.asc; sleep 1
./ansiu asc/cloud.asc; sleep 1
./ansiu asc/cloud_circle.asc; sleep 1
./ansiu asc/cloud_done.asc; sleep 1
./ansiu asc/cloud_download.asc; sleep 1
./ansiu asc/cloud_off.asc; sleep 1
./ansiu asc/cloud_queue.asc; sleep 1
./ansiu asc/cloud_upload.asc; sleep 1
./ansiu asc/code.asc; sleep 1
./ansiu asc/collections.asc; sleep 1
./ansiu asc/collections_bookmark.asc; sleep 1
./ansiu asc/colorize.asc; sleep 1
./ansiu asc/color_lens.asc; sleep 1
./ansiu asc/comment.asc; sleep 1
./ansiu asc/compare_arrows.asc; sleep 1
./ansiu asc/compare.asc; sleep 1
./ansiu asc/computer.asc; sleep 1
./ansiu asc/confirmation_number.asc; sleep 1
./ansiu asc/contact_mail.asc; sleep 1
./ansiu asc/contact_phone.asc; sleep 1
./ansiu asc/contacts.asc; sleep 1
./ansiu asc/content_copy.asc; sleep 1
./ansiu asc/content_cut.asc; sleep 1
./ansiu asc/content_paste.asc; sleep 1
./ansiu asc/control_point.asc; sleep 1
./ansiu asc/control_point_duplicate.asc; sleep 1
./ansiu asc/copyright.asc; sleep 1
./ansiu asc/create.asc; sleep 1
./ansiu asc/create_new_folder.asc; sleep 1
./ansiu asc/credit_card.asc; sleep 1
./ansiu asc/crop_16_9.asc; sleep 1
./ansiu asc/crop_3_2.asc; sleep 1
./ansiu asc/crop_5_4.asc; sleep 1
./ansiu asc/crop_7_5.asc; sleep 1
./ansiu asc/crop.asc; sleep 1
./ansiu asc/crop_din.asc; sleep 1
./ansiu asc/crop_free.asc; sleep 1
./ansiu asc/crop_landscape.asc; sleep 1
./ansiu asc/crop_original.asc; sleep 1
./ansiu asc/crop_portrait.asc; sleep 1
./ansiu asc/crop_rotate.asc; sleep 1
./ansiu asc/crop_square.asc; sleep 1
./ansiu asc/dashboard.asc; sleep 1
./ansiu asc/data_usage.asc; sleep 1
./ansiu asc/date_range.asc; sleep 1
./ansiu asc/dehaze.asc; sleep 1
./ansiu asc/delete.asc; sleep 1
./ansiu asc/delete_forever.asc; sleep 1
./ansiu asc/delete_sweep.asc; sleep 1
./ansiu asc/description.asc; sleep 1
./ansiu asc/desktop_mac.asc; sleep 1
./ansiu asc/desktop_windows.asc; sleep 1
./ansiu asc/details.asc; sleep 1
./ansiu asc/developer_board.asc; sleep 1
./ansiu asc/developer_mode.asc; sleep 1
./ansiu asc/device_hub.asc; sleep 1
./ansiu asc/devices.asc; sleep 1
./ansiu asc/devices_other.asc; sleep 1
./ansiu asc/dialer_sip.asc; sleep 1
./ansiu asc/dialpad.asc; sleep 1
./ansiu asc/directions_bike.asc; sleep 1
./ansiu asc/directions.asc; sleep 1
./ansiu asc/directions_boat.asc; sleep 1
./ansiu asc/directions_bus.asc; sleep 1
./ansiu asc/directions_car.asc; sleep 1
./ansiu asc/directions_railway.asc; sleep 1
./ansiu asc/directions_run.asc; sleep 1
./ansiu asc/directions_subway.asc; sleep 1
./ansiu asc/directions_transit.asc; sleep 1
./ansiu asc/directions_walk.asc; sleep 1
./ansiu asc/disc_full.asc; sleep 1
./ansiu asc/dns.asc; sleep 1
./ansiu asc/dock.asc; sleep 1
./ansiu asc/domain.asc; sleep 1
./ansiu asc/done_all.asc; sleep 1
./ansiu asc/done.asc; sleep 1
./ansiu asc/do_not_disturb_alt.asc; sleep 1
./ansiu asc/do_not_disturb.asc; sleep 1
./ansiu asc/do_not_disturb_off.asc; sleep 1
./ansiu asc/do_not_disturb_on.asc; sleep 1
./ansiu asc/donut_large.asc; sleep 1
./ansiu asc/donut_small.asc; sleep 1
./ansiu asc/drafts.asc; sleep 1
./ansiu asc/drag_handle.asc; sleep 1
./ansiu asc/drive_eta.asc; sleep 1
./ansiu asc/dvr.asc; sleep 1
./ansiu asc/edit.asc; sleep 1
./ansiu asc/edit_location.asc; sleep 1
./ansiu asc/eject.asc; sleep 1
./ansiu asc/email.asc; sleep 1
./ansiu asc/enhanced_encryption.asc; sleep 1
./ansiu asc/equalizer.asc; sleep 1
./ansiu asc/error.asc; sleep 1
./ansiu asc/error_outline.asc; sleep 1
./ansiu asc/euro_symbol.asc; sleep 1
./ansiu asc/event_available.asc; sleep 1
./ansiu asc/event.asc; sleep 1
./ansiu asc/event_busy.asc; sleep 1
./ansiu asc/event_note.asc; sleep 1
./ansiu asc/event_seat.asc; sleep 1
./ansiu asc/ev_station.asc; sleep 1
./ansiu asc/exit_to_app.asc; sleep 1
./ansiu asc/expand_less.asc; sleep 1
./ansiu asc/expand_more.asc; sleep 1
./ansiu asc/explicit.asc; sleep 1
./ansiu asc/explore.asc; sleep 1
./ansiu asc/exposure.asc; sleep 1
./ansiu asc/exposure_neg_1.asc; sleep 1
./ansiu asc/exposure_neg_2.asc; sleep 1
./ansiu asc/exposure_plus_1.asc; sleep 1
./ansiu asc/exposure_plus_2.asc; sleep 1
./ansiu asc/exposure_zero.asc; sleep 1
./ansiu asc/extension.asc; sleep 1
./ansiu asc/face.asc; sleep 1
./ansiu asc/fast_forward.asc; sleep 1
./ansiu asc/fast_rewind.asc; sleep 1
./ansiu asc/favorite.asc; sleep 1
./ansiu asc/favorite_border.asc; sleep 1
./ansiu asc/featured_play_list.asc; sleep 1
./ansiu asc/featured_video.asc; sleep 1
./ansiu asc/feedback.asc; sleep 1
./ansiu asc/fiber_dvr.asc; sleep 1
./ansiu asc/fiber_manual_record.asc; sleep 1
./ansiu asc/fiber_new.asc; sleep 1
./ansiu asc/fiber_pin.asc; sleep 1
./ansiu asc/fiber_smart_record.asc; sleep 1
./ansiu asc/file_download.asc; sleep 1
./ansiu asc/file_upload.asc; sleep 1
./ansiu asc/filter_1.asc; sleep 1
./ansiu asc/filter_2.asc; sleep 1
./ansiu asc/filter_3.asc; sleep 1
./ansiu asc/filter_4.asc; sleep 1
./ansiu asc/filter_5.asc; sleep 1
./ansiu asc/filter_6.asc; sleep 1
./ansiu asc/filter_7.asc; sleep 1
./ansiu asc/filter_8.asc; sleep 1
./ansiu asc/filter_9.asc; sleep 1
./ansiu asc/filter_9_plus.asc; sleep 1
./ansiu asc/filter_b_and_w.asc; sleep 1
./ansiu asc/filter.asc; sleep 1
./ansiu asc/filter_center_focus.asc; sleep 1
./ansiu asc/filter_drama.asc; sleep 1
./ansiu asc/filter_frames.asc; sleep 1
./ansiu asc/filter_hdr.asc; sleep 1
./ansiu asc/filter_list.asc; sleep 1
./ansiu asc/filter_none.asc; sleep 1
./ansiu asc/filter_tilt_shift.asc; sleep 1
./ansiu asc/filter_vintage.asc; sleep 1
./ansiu asc/find_in_page.asc; sleep 1
./ansiu asc/find_replace.asc; sleep 1
./ansiu asc/fingerprint.asc; sleep 1
./ansiu asc/first_page.asc; sleep 1
./ansiu asc/fitness_center.asc; sleep 1
./ansiu asc/flag.asc; sleep 1
./ansiu asc/flare.asc; sleep 1
./ansiu asc/flash_auto.asc; sleep 1
./ansiu asc/flash_off.asc; sleep 1
./ansiu asc/flash_on.asc; sleep 1
./ansiu asc/flight.asc; sleep 1
./ansiu asc/flight_land.asc; sleep 1
./ansiu asc/flight_takeoff.asc; sleep 1
./ansiu asc/flip.asc; sleep 1
./ansiu asc/flip_to_back.asc; sleep 1
./ansiu asc/flip_to_front.asc; sleep 1
./ansiu asc/folder.asc; sleep 1
./ansiu asc/folder_open.asc; sleep 1
./ansiu asc/folder_shared.asc; sleep 1
./ansiu asc/folder_special.asc; sleep 1
./ansiu asc/font_download.asc; sleep 1
./ansiu asc/format_align_center.asc; sleep 1
./ansiu asc/format_align_justify.asc; sleep 1
./ansiu asc/format_align_left.asc; sleep 1
./ansiu asc/format_align_right.asc; sleep 1
./ansiu asc/format_bold.asc; sleep 1
./ansiu asc/format_clear.asc; sleep 1
./ansiu asc/format_color_fill.asc; sleep 1
./ansiu asc/format_color_reset.asc; sleep 1
./ansiu asc/format_color_text.asc; sleep 1
./ansiu asc/format_indent_decrease.asc; sleep 1
./ansiu asc/format_indent_increase.asc; sleep 1
./ansiu asc/format_italblack.asc; sleep 1
./ansiu asc/format_line_spacing.asc; sleep 1
./ansiu asc/format_list_bulleted.asc; sleep 1
./ansiu asc/format_list_numbered.asc; sleep 1
./ansiu asc/format_paint.asc; sleep 1
./ansiu asc/format_quote.asc; sleep 1
./ansiu asc/format_shapes.asc; sleep 1
./ansiu asc/format_size.asc; sleep 1
./ansiu asc/format_strikethrough.asc; sleep 1
./ansiu asc/format_textdirection_l_to_r.asc; sleep 1
./ansiu asc/format_textdirection_r_to_l.asc; sleep 1
./ansiu asc/format_underlined.asc; sleep 1
./ansiu asc/forum.asc; sleep 1
./ansiu asc/forward_10.asc; sleep 1
./ansiu asc/forward_30.asc; sleep 1
./ansiu asc/forward_5.asc; sleep 1
./ansiu asc/forward.asc; sleep 1
./ansiu asc/free_breakfast.asc; sleep 1
./ansiu asc/fullscreen.asc; sleep 1
./ansiu asc/fullscreen_exit.asc; sleep 1
./ansiu asc/functions.asc; sleep 1
./ansiu asc/gamepad.asc; sleep 1
./ansiu asc/games.asc; sleep 1
./ansiu asc/gavel.asc; sleep 1
./ansiu asc/gesture.asc; sleep 1
./ansiu asc/get_app.asc; sleep 1
./ansiu asc/gif.asc; sleep 1
./ansiu asc/golf_course.asc; sleep 1
./ansiu asc/gps_fixed.asc; sleep 1
./ansiu asc/gps_not_fixed.asc; sleep 1
./ansiu asc/gps_off.asc; sleep 1
./ansiu asc/grade.asc; sleep 1
./ansiu asc/gradient.asc; sleep 1
./ansiu asc/grain.asc; sleep 1
./ansiu asc/grapheq.asc; sleep 1
./ansiu asc/grid_off.asc; sleep 1
./ansiu asc/grid_on.asc; sleep 1
./ansiu asc/group_add.asc; sleep 1
./ansiu asc/group.asc; sleep 1
./ansiu asc/group_work.asc; sleep 1
./ansiu asc/g_translate.asc; sleep 1
./ansiu asc/hd.asc; sleep 1
./ansiu asc/hdr_off.asc; sleep 1
./ansiu asc/hdr_on.asc; sleep 1
./ansiu asc/hdr_strong.asc; sleep 1
./ansiu asc/hdr_weak.asc; sleep 1
./ansiu asc/headset.asc; sleep 1
./ansiu asc/headset_mblack.asc; sleep 1
./ansiu asc/healing.asc; sleep 1
./ansiu asc/hearing.asc; sleep 1
./ansiu asc/help.asc; sleep 1
./ansiu asc/help_outline.asc; sleep 1
./ansiu asc/highlight.asc; sleep 1
./ansiu asc/highlight_off.asc; sleep 1
./ansiu asc/high_quality.asc; sleep 1
./ansiu asc/history.asc; sleep 1
./ansiu asc/home.asc; sleep 1
./ansiu asc/hotel.asc; sleep 1
./ansiu asc/hot_tub.asc; sleep 1
./ansiu asc/hourglass_empty.asc; sleep 1
./ansiu asc/hourglass_full.asc; sleep 1
./ansiu asc/http.asc; sleep 1
./ansiu asc/https.asc; sleep 1
./ansiu asc/image_aspect_ratio.asc; sleep 1
./ansiu asc/image.asc; sleep 1
./ansiu asc/important_devices.asc; sleep 1
./ansiu asc/import_contacts.asc; sleep 1
./ansiu asc/import_export.asc; sleep 1
./ansiu asc/inbox.asc; sleep 1
./ansiu asc/indeterminate_check_box.asc; sleep 1
./ansiu asc/info.asc; sleep 1
./ansiu asc/info_outline.asc; sleep 1
./ansiu asc/input.asc; sleep 1
./ansiu asc/insert_chart.asc; sleep 1
./ansiu asc/insert_comment.asc; sleep 1
./ansiu asc/insert_drive_file.asc; sleep 1
./ansiu asc/insert_emoticon.asc; sleep 1
./ansiu asc/insert_invitation.asc; sleep 1
./ansiu asc/insert_link.asc; sleep 1
./ansiu asc/insert_photo.asc; sleep 1
./ansiu asc/invert_colors.asc; sleep 1
./ansiu asc/invert_colors_off.asc; sleep 1
./ansiu asc/iso.asc; sleep 1
./ansiu asc/keyboard_arrow_down.asc; sleep 1
./ansiu asc/keyboard_arrow_left.asc; sleep 1
./ansiu asc/keyboard_arrow_right.asc; sleep 1
./ansiu asc/keyboard_arrow_up.asc; sleep 1
./ansiu asc/keyboard_backspace.asc; sleep 1
./ansiu asc/keyboard.asc; sleep 1
./ansiu asc/keyboard_capslock.asc; sleep 1
./ansiu asc/keyboard_hide.asc; sleep 1
./ansiu asc/keyboard_return.asc; sleep 1
./ansiu asc/keyboard_tab.asc; sleep 1
./ansiu asc/keyboard_voice.asc; sleep 1
./ansiu asc/kitchen.asc; sleep 1
./ansiu asc/label.asc; sleep 1
./ansiu asc/label_outline.asc; sleep 1
./ansiu asc/landscape.asc; sleep 1
./ansiu asc/language.asc; sleep 1
./ansiu asc/laptop.asc; sleep 1
./ansiu asc/laptop_chromebook.asc; sleep 1
./ansiu asc/laptop_mac.asc; sleep 1
./ansiu asc/laptop_windows.asc; sleep 1
./ansiu asc/last_page.asc; sleep 1
./ansiu asc/launch.asc; sleep 1
./ansiu asc/layers.asc; sleep 1
./ansiu asc/layers_clear.asc; sleep 1
./ansiu asc/leak_add.asc; sleep 1
./ansiu asc/leak_remove.asc; sleep 1
./ansiu asc/lens.asc; sleep 1
./ansiu asc/library_add.asc; sleep 1
./ansiu asc/library_books.asc; sleep 1
./ansiu asc/library_musblack.asc; sleep 1
./ansiu asc/lightbulb_outline.asc; sleep 1
./ansiu asc/linear_scale.asc; sleep 1
./ansiu asc/line_style.asc; sleep 1
./ansiu asc/line_weight.asc; sleep 1
./ansiu asc/link.asc; sleep 1
./ansiu asc/linked_camera.asc; sleep 1
./ansiu asc/list.asc; sleep 1
./ansiu asc/live_help.asc; sleep 1
./ansiu asc/live_tv.asc; sleep 1
./ansiu asc/local_activity.asc; sleep 1
./ansiu asc/local_airport.asc; sleep 1
./ansiu asc/local_atm.asc; sleep 1
./ansiu asc/local_bar.asc; sleep 1
./ansiu asc/local_cafe.asc; sleep 1
./ansiu asc/local_car_wash.asc; sleep 1
./ansiu asc/local_convenience_store.asc; sleep 1
./ansiu asc/local_dining.asc; sleep 1
./ansiu asc/local_drink.asc; sleep 1
./ansiu asc/local_florist.asc; sleep 1
./ansiu asc/local_gas_station.asc; sleep 1
./ansiu asc/local_grocery_store.asc; sleep 1
./ansiu asc/local_hospital.asc; sleep 1
./ansiu asc/local_hotel.asc; sleep 1
./ansiu asc/local_laundry_service.asc; sleep 1
./ansiu asc/local_library.asc; sleep 1
./ansiu asc/local_mall.asc; sleep 1
./ansiu asc/local_movies.asc; sleep 1
./ansiu asc/local_offer.asc; sleep 1
./ansiu asc/local_parking.asc; sleep 1
./ansiu asc/local_pharmacy.asc; sleep 1
./ansiu asc/local_phone.asc; sleep 1
./ansiu asc/local_pizza.asc; sleep 1
./ansiu asc/local_play.asc; sleep 1
./ansiu asc/local_post_office.asc; sleep 1
./ansiu asc/local_printshop.asc; sleep 1
./ansiu asc/local_see.asc; sleep 1
./ansiu asc/local_shipping.asc; sleep 1
./ansiu asc/local_taxi.asc; sleep 1
./ansiu asc/location_city.asc; sleep 1
./ansiu asc/location_disabled.asc; sleep 1
./ansiu asc/location_off.asc; sleep 1
./ansiu asc/location_on.asc; sleep 1
./ansiu asc/location_searching.asc; sleep 1
./ansiu asc/lock.asc; sleep 1
./ansiu asc/lock_open.asc; sleep 1
./ansiu asc/lock_outline.asc; sleep 1
./ansiu asc/looks_3.asc; sleep 1
./ansiu asc/looks_4.asc; sleep 1
./ansiu asc/looks_5.asc; sleep 1
./ansiu asc/looks_6.asc; sleep 1
./ansiu asc/looks.asc; sleep 1
./ansiu asc/looks_one.asc; sleep 1
./ansiu asc/looks_two.asc; sleep 1
./ansiu asc/loop.asc; sleep 1
./ansiu asc/loupe.asc; sleep 1
./ansiu asc/low_priority.asc; sleep 1
./ansiu asc/loyalty.asc; sleep 1
./ansiu asc/mail.asc; sleep 1
./ansiu asc/mail_outline.asc; sleep 1
./ansiu asc/map.asc; sleep 1
./ansiu asc/markunread.asc; sleep 1
./ansiu asc/markunread_mailbox.asc; sleep 1
./ansiu asc/mblack.asc; sleep 1
./ansiu asc/memory.asc; sleep 1
./ansiu asc/menu.asc; sleep 1
./ansiu asc/merge_type.asc; sleep 1
./ansiu asc/message.asc; sleep 1
./ansiu asc/mms.asc; sleep 1
./ansiu asc/mnone.asc; sleep 1
./ansiu asc/mode_comment.asc; sleep 1
./ansiu asc/mode_edit.asc; sleep 1
./ansiu asc/moff.asc; sleep 1
./ansiu asc/monetization_on.asc; sleep 1
./ansiu asc/money_off.asc; sleep 1
./ansiu asc/monochrome_photos.asc; sleep 1
./ansiu asc/mood_bad.asc; sleep 1
./ansiu asc/mood.asc; sleep 1
./ansiu asc/more.asc; sleep 1
./ansiu asc/more_horiz.asc; sleep 1
./ansiu asc/more_vert.asc; sleep 1
./ansiu asc/motorcycle.asc; sleep 1
./ansiu asc/mouse.asc; sleep 1
./ansiu asc/move_to_inbox.asc; sleep 1
./ansiu asc/movie.asc; sleep 1
./ansiu asc/movie_creation.asc; sleep 1
./ansiu asc/movie_filter.asc; sleep 1
./ansiu asc/multiline_chart.asc; sleep 1
./ansiu asc/musnote.asc; sleep 1
./ansiu asc/musvideo.asc; sleep 1
./ansiu asc/my_location.asc; sleep 1
./ansiu asc/nature.asc; sleep 1
./ansiu asc/nature_people.asc; sleep 1
./ansiu asc/navigate_before.asc; sleep 1
./ansiu asc/navigate_next.asc; sleep 1
./ansiu asc/navigation.asc; sleep 1
./ansiu asc/near_me.asc; sleep 1
./ansiu asc/network_cell.asc; sleep 1
./ansiu asc/network_check.asc; sleep 1
./ansiu asc/network_locked.asc; sleep 1
./ansiu asc/network_wifi.asc; sleep 1
./ansiu asc/new_releases.asc; sleep 1
./ansiu asc/next_week.asc; sleep 1
./ansiu asc/nfc.asc; sleep 1
./ansiu asc/no_encryption.asc; sleep 1
./ansiu asc/no_sim.asc; sleep 1
./ansiu asc/note_add.asc; sleep 1
./ansiu asc/note.asc; sleep 1
./ansiu asc/notifications_active.asc; sleep 1
./ansiu asc/notifications.asc; sleep 1
./ansiu asc/notifications_none.asc; sleep 1
./ansiu asc/notifications_off.asc; sleep 1
./ansiu asc/notifications_paused.asc; sleep 1
./ansiu asc/not_interested.asc; sleep 1
./ansiu asc/offline_pin.asc; sleep 1
./ansiu asc/ondemand_video.asc; sleep 1
./ansiu asc/opacity.asc; sleep 1
./ansiu asc/open_in_browser.asc; sleep 1
./ansiu asc/open_in_new.asc; sleep 1
./ansiu asc/open_with.asc; sleep 1
./ansiu asc/pages.asc; sleep 1
./ansiu asc/pageview.asc; sleep 1
./ansiu asc/palette.asc; sleep 1
./ansiu asc/panorama.asc; sleep 1
./ansiu asc/panorama_fish_eye.asc; sleep 1
./ansiu asc/panorama_horizontal.asc; sleep 1
./ansiu asc/panorama_vertical.asc; sleep 1
./ansiu asc/panorama_wide_angle.asc; sleep 1
./ansiu asc/pan_tool.asc; sleep 1
./ansiu asc/party_mode.asc; sleep 1
./ansiu asc/pause.asc; sleep 1
./ansiu asc/pause_circle_filled.asc; sleep 1
./ansiu asc/pause_circle_outline.asc; sleep 1
./ansiu asc/payment.asc; sleep 1
./ansiu asc/people.asc; sleep 1
./ansiu asc/people_outline.asc; sleep 1
./ansiu asc/perm_camera_mblack.asc; sleep 1
./ansiu asc/perm_contact_calendar.asc; sleep 1
./ansiu asc/perm_data_setting.asc; sleep 1
./ansiu asc/perm_device_information.asc; sleep 1
./ansiu asc/perm_identity.asc; sleep 1
./ansiu asc/perm_media.asc; sleep 1
./ansiu asc/perm_phone_msg.asc; sleep 1
./ansiu asc/perm_scan_wifi.asc; sleep 1
./ansiu asc/person_add.asc; sleep 1
./ansiu asc/personal_video.asc; sleep 1
./ansiu asc/person.asc; sleep 1
./ansiu asc/person_outline.asc; sleep 1
./ansiu asc/person_pin.asc; sleep 1
./ansiu asc/person_pin_circle.asc; sleep 1
./ansiu asc/pets.asc; sleep 1
./ansiu asc/phone_android.asc; sleep 1
./ansiu asc/phone.asc; sleep 1
./ansiu asc/phone_bluetooth_speaker.asc; sleep 1
./ansiu asc/phone_forwarded.asc; sleep 1
./ansiu asc/phone_in_talk.asc; sleep 1
./ansiu asc/phone_iphone.asc; sleep 1
./ansiu asc/phonelink.asc; sleep 1
./ansiu asc/phonelink_erase.asc; sleep 1
./ansiu asc/phonelink_lock.asc; sleep 1
./ansiu asc/phonelink_off.asc; sleep 1
./ansiu asc/phonelink_ring.asc; sleep 1
./ansiu asc/phonelink_setup.asc; sleep 1
./ansiu asc/phone_locked.asc; sleep 1
./ansiu asc/phone_missed.asc; sleep 1
./ansiu asc/phone_paused.asc; sleep 1
./ansiu asc/photo_album.asc; sleep 1
./ansiu asc/photo.asc; sleep 1
./ansiu asc/photo_camera.asc; sleep 1
./ansiu asc/photo_filter.asc; sleep 1
./ansiu asc/photo_library.asc; sleep 1
./ansiu asc/photo_size_select_actual.asc; sleep 1
./ansiu asc/photo_size_select_large.asc; sleep 1
./ansiu asc/photo_size_select_small.asc; sleep 1
./ansiu asc/picture_as_pdf.asc; sleep 1
./ansiu asc/picture_in_picture_alt.asc; sleep 1
./ansiu asc/picture_in_picture.asc; sleep 1
./ansiu asc/pie_chart.asc; sleep 1
./ansiu asc/pie_chart_outlined.asc; sleep 1
./ansiu asc/pin_drop.asc; sleep 1
./ansiu asc/place.asc; sleep 1
./ansiu asc/play_arrow.asc; sleep 1
./ansiu asc/play_circle_filled.asc; sleep 1
./ansiu asc/play_circle_filled_white.asc; sleep 1
./ansiu asc/play_circle_outline.asc; sleep 1
./ansiu asc/play_for_work.asc; sleep 1
./ansiu asc/playlist_add.asc; sleep 1
./ansiu asc/playlist_add_check.asc; sleep 1
./ansiu asc/playlist_play.asc; sleep 1
./ansiu asc/plus_one.asc; sleep 1
./ansiu asc/poll.asc; sleep 1
./ansiu asc/polymer.asc; sleep 1
./ansiu asc/pool.asc; sleep 1
./ansiu asc/portable_wifi_off.asc; sleep 1
./ansiu asc/portrait.asc; sleep 1
./ansiu asc/power.asc; sleep 1
./ansiu asc/power_input.asc; sleep 1
./ansiu asc/power_settings_new.asc; sleep 1
./ansiu asc/pregnant_woman.asc; sleep 1
./ansiu asc/present_to_all.asc; sleep 1
./ansiu asc/print.asc; sleep 1
./ansiu asc/priority_high.asc; sleep 1
./ansiu asc/publblack.asc; sleep 1
./ansiu asc/publish.asc; sleep 1
./ansiu asc/query_builder.asc; sleep 1
./ansiu asc/question_answer.asc; sleep 1
./ansiu asc/queue.asc; sleep 1
./ansiu asc/queue_musblack.asc; sleep 1
./ansiu asc/queue_play_next.asc; sleep 1
./ansiu asc/radio.asc; sleep 1
./ansiu asc/radio_button_checked.asc; sleep 1
./ansiu asc/radio_button_unchecked.asc; sleep 1
./ansiu asc/rate_review.asc; sleep 1
./ansiu asc/receipt.asc; sleep 1
./ansiu asc/recent_actors.asc; sleep 1
./ansiu asc/record_voice_over.asc; sleep 1
./ansiu asc/redeem.asc; sleep 1
./ansiu asc/redo.asc; sleep 1
./ansiu asc/refresh.asc; sleep 1
./ansiu asc/remove.asc; sleep 1
./ansiu asc/remove_circle.asc; sleep 1
./ansiu asc/remove_circle_outline.asc; sleep 1
./ansiu asc/remove_from_queue.asc; sleep 1
./ansiu asc/remove_red_eye.asc; sleep 1
./ansiu asc/remove_shopping_cart.asc; sleep 1
./ansiu asc/reorder.asc; sleep 1
./ansiu asc/repeat.asc; sleep 1
./ansiu asc/repeat_one.asc; sleep 1
./ansiu asc/replay_10.asc; sleep 1
./ansiu asc/replay_30.asc; sleep 1
./ansiu asc/replay_5.asc; sleep 1
./ansiu asc/replay.asc; sleep 1
./ansiu asc/reply_all.asc; sleep 1
./ansiu asc/reply.asc; sleep 1
./ansiu asc/report.asc; sleep 1
./ansiu asc/report_problem.asc; sleep 1
./ansiu asc/restaurant.asc; sleep 1
./ansiu asc/restaurant_menu.asc; sleep 1
./ansiu asc/restore.asc; sleep 1
./ansiu asc/restore_page.asc; sleep 1
./ansiu asc/ring_volume.asc; sleep 1
./ansiu asc/room.asc; sleep 1
./ansiu asc/room_service.asc; sleep 1
./ansiu asc/rotate_90_degrees_ccw.asc; sleep 1
./ansiu asc/rotate_left.asc; sleep 1
./ansiu asc/rotate_right.asc; sleep 1
./ansiu asc/rounded_corner.asc; sleep 1
./ansiu asc/router.asc; sleep 1
./ansiu asc/rowing.asc; sleep 1
./ansiu asc/rss_feed.asc; sleep 1
./ansiu asc/rv_hookup.asc; sleep 1
./ansiu asc/satellite.asc; sleep 1
./ansiu asc/save.asc; sleep 1
./ansiu asc/scanner.asc; sleep 1
./ansiu asc/schedule.asc; sleep 1
./ansiu asc/school.asc; sleep 1
./ansiu asc/screen_lock_landscape.asc; sleep 1
./ansiu asc/screen_lock_portrait.asc; sleep 1
./ansiu asc/screen_lock_rotation.asc; sleep 1
./ansiu asc/screen_rotation.asc; sleep 1
./ansiu asc/screen_share.asc; sleep 1
./ansiu asc/sd_card.asc; sleep 1
./ansiu asc/sd_storage.asc; sleep 1
./ansiu asc/search.asc; sleep 1
./ansiu asc/security.asc; sleep 1
./ansiu asc/select_all.asc; sleep 1
./ansiu asc/send.asc; sleep 1
./ansiu asc/sentiment_dissatisfied.asc; sleep 1
./ansiu asc/sentiment_neutral.asc; sleep 1
./ansiu asc/sentiment_satisfied.asc; sleep 1
./ansiu asc/sentiment_very_dissatisfied.asc; sleep 1
./ansiu asc/sentiment_very_satisfied.asc; sleep 1
./ansiu asc/settings_applications.asc; sleep 1
./ansiu asc/settings_backup_restore.asc; sleep 1
./ansiu asc/settings.asc; sleep 1
./ansiu asc/settings_bluetooth.asc; sleep 1
./ansiu asc/settings_brightness.asc; sleep 1
./ansiu asc/settings_cell.asc; sleep 1
./ansiu asc/settings_ethernet.asc; sleep 1
./ansiu asc/settings_input_antenna.asc; sleep 1
./ansiu asc/settings_input_component.asc; sleep 1
./ansiu asc/settings_input_composite.asc; sleep 1
./ansiu asc/settings_input_hdmi.asc; sleep 1
./ansiu asc/settings_input_svideo.asc; sleep 1
./ansiu asc/settings_overscan.asc; sleep 1
./ansiu asc/settings_phone.asc; sleep 1
./ansiu asc/settings_power.asc; sleep 1
./ansiu asc/settings_remote.asc; sleep 1
./ansiu asc/settings_system_daydream.asc; sleep 1
./ansiu asc/settings_voice.asc; sleep 1
./ansiu asc/share.asc; sleep 1
./ansiu asc/shop.asc; sleep 1
./ansiu asc/shopping_basket.asc; sleep 1
./ansiu asc/shopping_cart.asc; sleep 1
./ansiu asc/shop_two.asc; sleep 1
./ansiu asc/short_text.asc; sleep 1
./ansiu asc/show_chart.asc; sleep 1
./ansiu asc/shuffle.asc; sleep 1
./ansiu asc/signal_cellular_0_bar.asc; sleep 1
./ansiu asc/signal_cellular_1_bar.asc; sleep 1
./ansiu asc/signal_cellular_2_bar.asc; sleep 1
./ansiu asc/signal_cellular_3_bar.asc; sleep 1
./ansiu asc/signal_cellular_4_bar.asc; sleep 1
./ansiu asc/signal_cellular_connected_no_internet_0_bar.asc; sleep 1
./ansiu asc/signal_cellular_connected_no_internet_1_bar.asc; sleep 1
./ansiu asc/signal_cellular_connected_no_internet_2_bar.asc; sleep 1
./ansiu asc/signal_cellular_connected_no_internet_3_bar.asc; sleep 1
./ansiu asc/signal_cellular_connected_no_internet_4_bar.asc; sleep 1
./ansiu asc/signal_cellular_no_sim.asc; sleep 1
./ansiu asc/signal_cellular_null.asc; sleep 1
./ansiu asc/signal_cellular_off.asc; sleep 1
./ansiu asc/signal_wifi_0_bar.asc; sleep 1
./ansiu asc/signal_wifi_1_bar.asc; sleep 1
./ansiu asc/signal_wifi_1_bar_lock.asc; sleep 1
./ansiu asc/signal_wifi_2_bar.asc; sleep 1
./ansiu asc/signal_wifi_2_bar_lock.asc; sleep 1
./ansiu asc/signal_wifi_3_bar.asc; sleep 1
./ansiu asc/signal_wifi_3_bar_lock.asc; sleep 1
./ansiu asc/signal_wifi_4_bar.asc; sleep 1
./ansiu asc/signal_wifi_4_bar_lock.asc; sleep 1
./ansiu asc/signal_wifi_off.asc; sleep 1
./ansiu asc/sim_card_alert.asc; sleep 1
./ansiu asc/sim_card.asc; sleep 1
./ansiu asc/skip_next.asc; sleep 1
./ansiu asc/skip_previous.asc; sleep 1
./ansiu asc/slideshow.asc; sleep 1
./ansiu asc/slow_motion_video.asc; sleep 1
./ansiu asc/smartphone.asc; sleep 1
./ansiu asc/smoke_free.asc; sleep 1
./ansiu asc/smoking_rooms.asc; sleep 1
./ansiu asc/sms.asc; sleep 1
./ansiu asc/sms_failed.asc; sleep 1
./ansiu asc/snooze.asc; sleep 1
./ansiu asc/sort.asc; sleep 1
./ansiu asc/sort_by_alpha.asc; sleep 1
./ansiu asc/spa.asc; sleep 1
./ansiu asc/space_bar.asc; sleep 1
./ansiu asc/speaker.asc; sleep 1
./ansiu asc/speaker_group.asc; sleep 1
./ansiu asc/speaker_notes.asc; sleep 1
./ansiu asc/speaker_notes_off.asc; sleep 1
./ansiu asc/speaker_phone.asc; sleep 1
./ansiu asc/spellcheck.asc; sleep 1
./ansiu asc/star.asc; sleep 1
./ansiu asc/star_border.asc; sleep 1
./ansiu asc/star_half.asc; sleep 1
./ansiu asc/stars.asc; sleep 1
./ansiu asc/stay_current_landscape.asc; sleep 1
./ansiu asc/stay_current_portrait.asc; sleep 1
./ansiu asc/stay_primary_landscape.asc; sleep 1
./ansiu asc/stay_primary_portrait.asc; sleep 1
./ansiu asc/stop.asc; sleep 1
./ansiu asc/stop_screen_share.asc; sleep 1
./ansiu asc/storage.asc; sleep 1
./ansiu asc/store.asc; sleep 1
./ansiu asc/store_mall_directory.asc; sleep 1
./ansiu asc/straighten.asc; sleep 1
./ansiu asc/streetview.asc; sleep 1
./ansiu asc/strikethrough_s.asc; sleep 1
./ansiu asc/style.asc; sleep 1
./ansiu asc/subdirectory_arrow_left.asc; sleep 1
./ansiu asc/subdirectory_arrow_right.asc; sleep 1
./ansiu asc/subject.asc; sleep 1
./ansiu asc/subscriptions.asc; sleep 1
./ansiu asc/subtitles.asc; sleep 1
./ansiu asc/subway.asc; sleep 1
./ansiu asc/supervisor_account.asc; sleep 1
./ansiu asc/surround_sound.asc; sleep 1
./ansiu asc/swap_calls.asc; sleep 1
./ansiu asc/swap_horiz.asc; sleep 1
./ansiu asc/swap_vert.asc; sleep 1
./ansiu asc/swap_vertical_circle.asc; sleep 1
./ansiu asc/switch_camera.asc; sleep 1
./ansiu asc/switch_video.asc; sleep 1
./ansiu asc/sync.asc; sleep 1
./ansiu asc/sync_disabled.asc; sleep 1
./ansiu asc/sync_problem.asc; sleep 1
./ansiu asc/system_update_alt.asc; sleep 1
./ansiu asc/system_update.asc; sleep 1
./ansiu asc/tab.asc; sleep 1
./ansiu asc/tablet_android.asc; sleep 1
./ansiu asc/tablet.asc; sleep 1
./ansiu asc/tablet_mac.asc; sleep 1
./ansiu asc/tab_unselected.asc; sleep 1
./ansiu asc/tag_faces.asc; sleep 1
./ansiu asc/tap_and_play.asc; sleep 1
./ansiu asc/terrain.asc; sleep 1
./ansiu asc/text_fields.asc; sleep 1
./ansiu asc/text_format.asc; sleep 1
./ansiu asc/textsms.asc; sleep 1
./ansiu asc/texture.asc; sleep 1
./ansiu asc/theaters.asc; sleep 1
./ansiu asc/thumb_down.asc; sleep 1
./ansiu asc/thumbs_up_down.asc; sleep 1
./ansiu asc/thumb_up.asc; sleep 1
./ansiu asc/timelapse.asc; sleep 1
./ansiu asc/timeline.asc; sleep 1
./ansiu asc/timer_10.asc; sleep 1
./ansiu asc/timer_3.asc; sleep 1
./ansiu asc/timer.asc; sleep 1
./ansiu asc/timer_off.asc; sleep 1
./ansiu asc/time_to_leave.asc; sleep 1
./ansiu asc/title.asc; sleep 1
./ansiu asc/toc.asc; sleep 1
./ansiu asc/today.asc; sleep 1
./ansiu asc/toll.asc; sleep 1
./ansiu asc/tonality.asc; sleep 1
./ansiu asc/touch_app.asc; sleep 1
./ansiu asc/toys.asc; sleep 1
./ansiu asc/track_changes.asc; sleep 1
./ansiu asc/traffblack.asc; sleep 1
./ansiu asc/train.asc; sleep 1
./ansiu asc/tram.asc; sleep 1
./ansiu asc/transfer_within_a_station.asc; sleep 1
./ansiu asc/transform.asc; sleep 1
./ansiu asc/translate.asc; sleep 1
./ansiu asc/trending_down.asc; sleep 1
./ansiu asc/trending_flat.asc; sleep 1
./ansiu asc/trending_up.asc; sleep 1
./ansiu asc/tune.asc; sleep 1
./ansiu asc/turned_in.asc; sleep 1
./ansiu asc/turned_in_not.asc; sleep 1
./ansiu asc/tv.asc; sleep 1
./ansiu asc/unarchive.asc; sleep 1
./ansiu asc/undo.asc; sleep 1
./ansiu asc/unfold_less.asc; sleep 1
./ansiu asc/unfold_more.asc; sleep 1
./ansiu asc/update.asc; sleep 1
./ansiu asc/usb.asc; sleep 1
./ansiu asc/verified_user.asc; sleep 1
./ansiu asc/vertical_align_bottom.asc; sleep 1
./ansiu asc/vertical_align_center.asc; sleep 1
./ansiu asc/vertical_align_top.asc; sleep 1
./ansiu asc/vibration.asc; sleep 1
./ansiu asc/video_call.asc; sleep 1
./ansiu asc/videocam.asc; sleep 1
./ansiu asc/videocam_off.asc; sleep 1
./ansiu asc/videogame_asset.asc; sleep 1
./ansiu asc/video_label.asc; sleep 1
./ansiu asc/video_library.asc; sleep 1
./ansiu asc/view_agenda.asc; sleep 1
./ansiu asc/view_array.asc; sleep 1
./ansiu asc/view_carousel.asc; sleep 1
./ansiu asc/view_column.asc; sleep 1
./ansiu asc/view_comfy.asc; sleep 1
./ansiu asc/view_compact.asc; sleep 1
./ansiu asc/view_day.asc; sleep 1
./ansiu asc/view_headline.asc; sleep 1
./ansiu asc/view_list.asc; sleep 1
./ansiu asc/view_module.asc; sleep 1
./ansiu asc/view_quilt.asc; sleep 1
./ansiu asc/view_stream.asc; sleep 1
./ansiu asc/view_week.asc; sleep 1
./ansiu asc/vignette.asc; sleep 1
./ansiu asc/visibility.asc; sleep 1
./ansiu asc/visibility_off.asc; sleep 1
./ansiu asc/voice_chat.asc; sleep 1
./ansiu asc/voicemail.asc; sleep 1
./ansiu asc/volume_down.asc; sleep 1
./ansiu asc/volume_mute.asc; sleep 1
./ansiu asc/volume_off.asc; sleep 1
./ansiu asc/volume_up.asc; sleep 1
./ansiu asc/vpn_key.asc; sleep 1
./ansiu asc/vpn_lock.asc; sleep 1
./ansiu asc/wallpaper.asc; sleep 1
./ansiu asc/warning.asc; sleep 1
./ansiu asc/watch.asc; sleep 1
./ansiu asc/watch_later.asc; sleep 1
./ansiu asc/wb_auto.asc; sleep 1
./ansiu asc/wb_cloudy.asc; sleep 1
./ansiu asc/wb_incandescent.asc; sleep 1
./ansiu asc/wb_iridescent.asc; sleep 1
./ansiu asc/wb_sunny.asc; sleep 1
./ansiu asc/wc.asc; sleep 1
./ansiu asc/web_asset.asc; sleep 1
./ansiu asc/web.asc; sleep 1
./ansiu asc/weekend.asc; sleep 1
./ansiu asc/whatshot.asc; sleep 1
./ansiu asc/widgets.asc; sleep 1
./ansiu asc/wifi.asc; sleep 1
./ansiu asc/wifi_lock.asc; sleep 1
./ansiu asc/wifi_tethering.asc; sleep 1
./ansiu asc/work.asc; sleep 1
./ansiu asc/wrap_text.asc; sleep 1
./ansiu asc/youtube_searched_for.asc; sleep 1
./ansiu asc/zoom_in.asc; sleep 1
./ansiu asc/zoom_out.asc; sleep 1
./ansiu asc/zoom_out_map.asc; sleep 1
